title: Rakin's Page
description: My markdown-powered website
baseurl: ""
url: "https://towfiq-rakin.github.io"
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts: {}
mathjax: true
